config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
   
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :followings
      get :followers
      get :likes
    end
  end
  
  resources :simpleposts, only: [:create, :destroy] do
    collection do
      get :search
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  mount_uploader :image, ImageUploader
  validates :alias_name, presence: true,                      # 空でないこと
                         length: { in: 5..15 },               # 長さ5～15文字であること
                         format: { with: /\A[a-z0-9_]+\z/i},  # 英数アンダースコアのみ
                         uniqueness: true                     # 一意であること
  validates :name, presence: true, length: { maximum: 50 }
  validates :self_introduction, length: { maximum: 500 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
                    
  has_secure_password
  
  has_many :simpleposts
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  has_many :favorites
  has_many :likes, through: :favorites, source: :simplepost
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def favorite(simplepost)
    self.favorites.find_or_create_by(simplepost_id: simplepost.id)
  end

  def unfavorite(simplepost)
    favorite = self.favorites.find_by(simplepost_id: simplepost.id)
    favorite.destroy if favorite
  end

  def likes?(simplepost)
    self.likes.include?simplepost
  end
  
  def feed_simpleposts
    Simplepost.where(user_id: self.following_ids + [self.id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :followings, :followers]
  before_action :correct_user, only: [:edit, :update]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])
    @simpleposts = @user.simpleposts.order(id: :desc).page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to :login
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end

  def likes
    @user = User.find(params[:id])
    @likes = @user.likes.page(params[:page])
    counts(@user)
  end
  
  def favoriters
    @user = User.find(params[:id])
    @favoriters = @user.favoriters.page(params[:page])
    counts(@user)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = 'プロフィールが更新されました'
      redirect_to @user
    else
      flash.now[:danger] = 'プロフィールは更新されませんでした'
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:alias_name, :name, :self_introduction, :email, :password, :password_confirmation, :image)
  end
  
  def correct_user
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to root_url
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/users/_edit_profile_button.html.erb
<% if current_user == user %>
  <%= link_to "プロフィール編集", edit_user_path, class: 'btn btn-secondary btn-sm' %>
<% end %>

app/views/users/_timeline.html.erb
<ul class="nav nav-tabs nav-justified mb-3">
  <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿  <span class="badge badge-secondary"><%= @count_simpleposts %></span></a></li>
  <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
  <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
  <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り  <span class="badge badge-secondary"><%= @count_likes %></span></a></li>
</ul>

app/views/users/_user_header.html.erb
  <div class="row">
    <div class="col-sm-3 offset-2 mt-2 mb-2">
      <h4><%= @user.name %> @<%= @user.alias_name %><h4>
      <% if @user.image? %>
        <img src='<%=  @user.image %>' class="icon" alt="ユーザーアイコン">
      <% else %>
        <image src="/assets/default.png" class="icon" alt="ユーザーアイコン" %>
      <% end %>
      <div class="mt-2">
        <%= render 'relationships/follow_button', user: @user %>
      </div>
    </div>
    <div class="col-sm-5 mt-4">
      <p><%= simple_format(@user.self_introduction) %></p>
    </div>
  </div>
  
  <div class="row">
    <div class="offset-8 mb-1">
      <%= render 'users/edit_profile_button', user: @user  %>
    </div>
  </div>

app/views/users/_users.html.erb
<% if users.any? %>
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <ul class="list-unstyled">
        <% users.each do |user| %>
          <li class="media">
            <% if user.image? %>
              <img class="mr-2 rounded icon" src='<%=  user.image %>' width="50px" height="50px" alt="ユーザーアイコン">
            <% else %>
              <image src="/assets/default.png" class=" mr-2 rounded icon" width="50px" height="50px" alt="ユーザーアイコン" %>
            <% end %>
            <div class="media-body">
              <div>
                <%= user.name %> <span class="text-muted"><%= "@" + user.alias_name %></span>
              </div>
              <div>
                <p><%= link_to 'プロフィールを見る', user_path(user) %></p>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <%= paginate users %>
<% end %>

app/views/users/edit.html.erb
<div class="text-center">
  <h1>プロフィールを編集</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <%= f.label :image, 'プロフィール画像' %>
      <div class="d-flex flex-row">
        <%= image_tag @user.image_url(:thumb ) if @user.image.present? %>
        <div class="form-group d-flex flex-column-reverse m-3">
          <%= f.file_field :image %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :self_introduction, '自己紹介' %>
        <%= f.text_area :self_introduction, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード(再入力)' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <div class="d-flex justify-content-center">
        <%= link_to '戻る', user_path(@user.id), class: 'btn btn-secondary mr-4' %>
        <%= f.submit '更新', class: 'btn btn-secondary ' %>
      </div>      
      
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container">
  <%= render 'user_header' %>
  <div class="row mt-2">
    <div class="col-sm-8 offset-2">
      <%= render 'timeline' %>
      <%= render 'users', users: @followers %>
    </div>
  </div>
</div>

app/views/users/followings.html.erb
<div class="container">
  <%= render 'user_header' %>
  <div class="row mt-2">
    <div class="col-sm-8 offset-2">
      <%= render 'timeline' %>
      <%= render 'users', users: @followings %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/likes.html.erb
<div class="container">
  <%= render 'user_header' %>
  <div class="row mt-2">
    <div class="col-sm-8 offset-2">
      <%= render 'timeline' %>
      <%= render 'simpleposts/simpleposts', simpleposts: @likes %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>アカウントを作成</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :alias_name, 'ID ※英数アンダーバー(_) 5～15桁' %>
        <%= f.text_field :alias_name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード(再入力)' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <%= f.submit '新規登録', class: 'btn btn-secondary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <%= render 'user_header' %>
  <div class="row mt-2">
    <div class="col-sm-8 offset-2">
      <%= render 'timeline' %>
      <%= render 'simpleposts/simpleposts', simpleposts: @simpleposts %>
    </div>
  </div>
</div>